version: "3.7"

services:
  app:
    image: app:2.1
    links:
      - mysql:mysql
    ports:
      - 80:5000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: flask
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
    healthcheck:
      test: ["CMD", "mysqladmin" ,"-uroot", "-proot", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
