---
service:
  name: todo-app
  type: LoadBalancer
  app: myapp
  protocol: TCP
  port: 80
  targetPort: 5000

todo_app:
  name: todo-app
  image: mfermie/myapp:1.0.2

mariadb:
  auth:
    rootPassword: testing123
    database: flask
  primary:
    name: mariadeebee
  fullnameOverride: mariadeebee
