apiVersion: v1
kind: Pod
metadata:
  labels:
    app: todo-mysql
  name: todo-mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: flask
    image: mysql:8
    name: todo-mysql
