apiVersion: v1
kind: Pod
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: todo
spec:
  containers:
  - env:
    - name: MYSQL_HOST
      value: mysql-myapp.todo.svc.cluster.local
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    - name: MYSQL_DB
      value: flask
    image: mfermie/myapp:1.0.0
    imagePullPolicy: IfNotPresent
    name: todo-app
